### ISSUE TITLE
warning: multiple methods named 'center' found [-Wobjc-multiple-method-names]

### ISSUE THREAD

**Issue by TimSatke** [OpenDiablo2/OpenDiablo2#171] opened 2019-11-14 12:44 UTC
**Describe the bug**
When first running `go run .` as in the README, I encounter an error.

**To Reproduce**
```console
$ go mod download
$ go run .
```
This is what I get:
```
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/c_glfw_darwin.go:8:
../../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190409004039-e6da0acd62b1/v3.2/glfw/glfw/src/cocoa_window.m:989:9: warning: multiple methods named 'center' found [-Wobjc-multiple-method-names]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCollectionViewCompositionalLayout.h:601:19: note: using
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:312:1: note: also found
```

**Expected behavior**
Something different, I don't know what's supposed to happen.

**Desktop (please complete the following information):**
<details>
<pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/tsatke/Library/Caches/go-build"
GOENV="/Users/tsatke/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tsatke/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tsatke/Development/OpenDiablo2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xm/r93t594n44v44v33td31nc1r0000gp/T/go-build916672717=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre>
</details>

**Comment by essial** [comment] 2019-11-14 22:31
This looks like it's coming from GLFW. If confirmed we can close this issue as we do not have control of this.

**Comment by essial** [comment] 2019-11-15 14:18
This looks like something specific to OSX Catalina. Is this what you are running? And are you not able to compile this in that version of OSX?

**Comment by TimSatke** [comment] 2019-11-15 19:21
Yes and positive.

**Comment by essial** [comment] 2019-11-15 19:28
Bjerre on our Discord chat was able to run in Catalina. I believe you when you say it's not working, so I'm curious as to the difference between your and his configurations.

**Comment by TimSatke** [comment] 2019-11-15 19:29
I’ve made no change, all I did was a cold start.

**Comment by AlexanderEkdahl** [comment] 2019-11-15 21:20
@TimSatke OpenDiablo2 should still run fine despite this problem.

Can you give me the output of `ls "/Applications/Diablo II"` please? I have a PR that adds support for macOS and I want to ensure I am loading everything correctly.

**Comment by TimSatke** [comment] 2019-11-15 21:34
Don’t have D2, just wanted to see it build. You are actually right though. The actual reason it doesn’t run is #170. 

So:
* OpenDiablo2 runs fine
* There is a GLFW warning

**Comment by freddy33** [comment] 2020-01-01 09:54
The issue was fixed in GLFW here: https://github.com/glfw/glfw/commit/bac15f94493938eded7161a7a0ab8827584e3db1
I think go-gl needs to upgrade before it'll be fixed here?

**Comment by essial** [comment] 2020-02-01 05:27
Closing as this is outside of this project's package.

**Closed by essial** 2020-02-01 05:27 UTC
Labels: question
