### ISSUE TITLE
Latest batch of commits lead to poor performance

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [OpenDiablo2/OpenDiablo2#199] opened 2019-11-17 08:42 UTC
With the latest batch of commits from today(and probably late yesterday), I get poor performance on map test. When scrolling the map with arrow keys, I get FPS of 5,6,7, wheres on static map it goes to 150-300 depending on the scene.

**Comment by averrin** [comment] 2019-11-17 10:02
I think the problem in drawing non-cached tiles. When you scroll over already seen regions, you have high fps.

**Comment by essial** [comment] 2019-11-17 12:56
Duplicate of #197

**Comment by essial** [comment] 2019-11-17 19:24
#202 should help, can anyone confirm?

**Comment by averrin** [comment] 2019-11-17 19:29
Loading time is much shorter and there aren't fps drops

**Comment by essial** [comment] 2019-11-17 21:06
@Dragomir-Ivanov Can you check with the latest merge and tell me how this runs for you?

**Comment by Dragomir-Ivanov** [comment] 2019-11-17 21:18
Just did that. It runs perfect. Fast scrolling, fast loads...until it crashed :)

Loading region: Act2/Town/LutW.ds1
panic: runtime error: index out of range

goroutine 58 [running]:
github.com/OpenDiablo2/OpenDiablo2/d2render.(*AnimatedEntity).Render(0xc00e054500, 0xc005837100, 0xffffffffffffff61, 0x334)
	/home/drago/go/src/github.com/OpenDiablo2/OpenDiablo2/d2render/animated_entity.go:164 +0x31d
github.com/OpenDiablo2/OpenDiablo2/d2core.(*NPC).Render(...)
	/home/drago/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/npc.go:30
github.com/OpenDiablo2/OpenDiablo2/d2render/d2mapengine.(*Engine).RenderPass2(0xc003a90420, 0xc00abea000, 0xfffffffffffffc90, 0xac8, 0x1d, 0x28, 0xc005837100)
	/home/drago/go/src/github.com/OpenDiablo2/OpenDiablo2/d2render/d2mapengine/engine.go:253 +0x34a
github.com/OpenDiablo2/OpenDiablo2/d2render/d2mapengine.(*Engine).RenderRegion(0xc003a90420, 0x0, 0x0, 0x39, 0x39, 0xc00abea000, 0xc000fc2000, 0xcb1, 0xf00, 0xc005837100)
	/home/drago/go/src/github.com/OpenDiablo2/OpenDiablo2/d2render/d2mapengine/engine.go:194 +0x2b5
github.com/OpenDiablo2/OpenDiablo2/d2render/d2mapengine.(*Engine).Render(0xc003a90420, 0xc005837100)
	/home/drago/go/src/github.com/OpenDiablo2/OpenDiablo2/d2render/d2mapengine/engine.go:127 +0x11c
github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene.(*MapEngineTest).Render(0xc0000b65a0, 0xc005837100)
	/home/drago/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/d2scene/map_engine_testing.go:174 +0x54
github.com/OpenDiablo2/OpenDiablo2/d2core.Engine.Draw(0xc0000ea100, 0xc000095b30, 0x0, 0xa00000001, 0xc000b2ca80, 0xa, 0xa, 0xffffffffffffffff, 0x0, 0x110, ...)
	/home/drago/go/src/github.com/OpenDiablo2/OpenDiablo2/d2core/engine.go:230 +0x99
main.update(0xc005837100, 0x0, 0x44800000)
	/home/drago/go/src/github.com/OpenDiablo2/OpenDiablo2/main.go:69 +0x9a
github.com/hajimehoshi/ebiten.(*imageDumper).update(0xc001ec82c0, 0xc005837100, 0x3, 0xc0005d3320)
	/home/drago/go/src/github.com/hajimehoshi/ebiten/imagedumper_desktop.go:105 +0x4e
github.com/hajimehoshi/ebiten.(*uiContext).Update(0xc001ec8300, 0xc01a1abe80, 0x0, 0x0)
	/home/drago/go/src/github.com/hajimehoshi/ebiten/uicontext.go:93 +0x150
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0xf2a8a0, 0x9f3c60, 0xc001ec8300, 0x0, 0x0)
	/home/drago/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:801 +0x1d6
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop(0xf2a8a0, 0x9f3c60, 0xc001ec8300, 0x0, 0x0)
	/home/drago/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:843 +0xc0
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).run(0xf2a8a0, 0x320, 0x258, 0x3ff0000000000000, 0xc0001481a0, 0x1a, 0x9f3c60, 0xc001ec8300, 0x40000, 0x108)
	/home/drago/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:701 +0x178
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run.func1(0xc0022ee0a0, 0xc0000726c0, 0xf2a8a0, 0x320, 0x258, 0x3ff0000000000000, 0xc0001481a0, 0x1a, 0x9f3c60, 0xc001ec8300)
	/home/drago/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:574 +0xd7
created by github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run
	/home/drago/go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:571 +0x1ca
^[[Dexit status 2

**Comment by essial** [comment] 2019-11-17 21:20
Yup you’re going to find those in random maps as we still don’t have all the logic done. A lot of it is info that simply doesn’t exist yet that we have to figure out the hard way.

**Comment by Dragomir-Ivanov** [comment] 2019-11-17 21:22
Just one note. Is it enough to for me to make
```
git pull
go get -u
``` 
in the `OpenDiablo2` root directory in order to get everything updated including `ebiten`?

**Comment by essial** [comment] 2019-11-17 21:23
I wouldn't say go get -u as that updates all module references as well. I'd stick with the refs we are currently using.
`git pull`
`go get .`
`go run .`
Should suffice.

**Comment by Dragomir-Ivanov** [comment] 2019-11-17 21:41
@essial Okay, thanks.

**Comment by essial** [comment] 2019-11-17 21:56
It does look like my changes introduced some regressions in the animation decoder. I’ll look into that over the next few days.

**Comment by essial** [comment] 2019-11-18 04:54
I'm closing this issue as I believe the performance has been fixed for the most part for now. We can open issues for the specific crashes.

**Closed by essial** 2019-11-18 04:54 UTC
